Capstone
roshan-bajgain/Conference-App pull request #1
Opened 2021-09-15 08:39 UTC by roshan-bajgain

Create new repo and add HTML, CSS, and js files and use a linter.
first, make a mobile page like the first page and the about page. 
Then implement those in the desktop version and using js first make a mobile menu and create the dynamic parts by javascript.

2021-09-15 10:00 UTC, henatan99 requested changes
Hi @roshan-bajgain , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] I cannot see any video recording link about the project either in your PR summary or the readme file. Kindly record video documentation about the project and provide the link either in your PR summary or your readme. :pray: 
- [x] You must add the Home page (index.html). The project requires a web app with two pages, the Home page, and the About page. Carefully follow the [project's requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md) and the [given design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) to build your Home page. :pray: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-15 10:00 UTC, henatan99 commented on README.md
> +
- [x] I think it is better to use a more descriptive title here than just "A Microverse capstone project". 
- [x] Kindly write a brief description of the project in the about section. Currently, users who visit your repo will not have a good picture of what the project is about.

2021-09-15 10:00 UTC, henatan99 commented on README.md
> +[Live Demo Link](https://roshan-bajgain.github.io/Conference-App/)
- [x] The live link displays just a copy of your readme content. It should be the app itself with Home and About pages with the contents and design shown in the original design reference. :pray: 

![Screenshot from 2021-09-15 15-22-26](https://user-images.githubusercontent.com/64894927/133407510-abc21da4-7f48-4305-8f6c-dfaad6aa6994.png)

2021-09-15 10:00 UTC, henatan99 commented on about.html
> +                        <li class="nav-item "><a href="index.html"><img id="logo" src="img/icons/logo.png"
- [x] There is no `index.html` file in your project. As a result, this link redirects to nowhere but to a blank browser window with an error message. 
![image](https://user-images.githubusercontent.com/64894927/133409146-47322058-8086-469f-bec7-88944e212c2a.png)

- [x] Kindly add the Home page (index.html) as the project requires the web app should have two pages, a Home page and About page.

2021-09-15 10:00 UTC, henatan99 commented on about.css
> +  color: orangered;
- [x] I think the right color here should be #f43d28. You can use color-picker google extension to get the colors from the design reference. 

![image](https://user-images.githubusercontent.com/64894927/133410524-5baa2665-ab82-4187-b3af-d3d394299989.png)
![image](https://user-images.githubusercontent.com/64894927/133410561-0c02478c-a7b5-40a4-ad27-d443013ccae5.png)

2021-09-15 10:00 UTC, henatan99 commented on about.html
> +                <div class="collapse navbar-collapse" id="navbarNavDropdown">
- [x] In the original design, the bottom bar contains a logo to the left.
- [x] In the original design, the bottom bar contains a list of page links aligned to the right.
- [x] Kindly align the logo to the left and the links to the right according to the design requirement. :pray: 

![image](https://user-images.githubusercontent.com/64894927/133411657-ea4ced6e-9a8a-4afe-b674-6431f96c9e37.png)

![image](https://user-images.githubusercontent.com/64894927/133411718-8f7e0017-4c95-4ad3-8189-58c599a0ae90.png)

2021-09-15 10:00 UTC, henatan99 commented on about.html
> +                </article>
- [x] This is a paragraph and semantically it is supposed to have a `p` tag. An article is kind of a wrapper that can have other `hx`, `p` 'img`, etc elements. Kindly make a change here. :pray:

2021-09-16 09:16 UTC, george-shammar requested changes
Hi @roshan-bajgain , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 09:16 UTC, george-shammar commented on README.md
> +
- [ ] In your video, you did not present any project. You simply talked about what you did. Please record another video and showcase your project by talking through what you did.

2021-09-17 08:17 UTC, Emmyn5600 approved these changes
Hi,

Good job so far! 👏🏼 @roshan-bajgain 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- You have a descriptive Readme file:heavy_check_mark:
- The live link is working properly:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous reviewers. 
 
 #### Optional suggestions
    
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-17 08:28 UTC, merged